name: celestia_air_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Core packages
  cupertino_icons: ^1.0.8       # For iOS style icons

  # Formatting and localization
  intl: ^0.19.0                # Updated to latest version for date formatting

  # Video playback
  video_player: ^2.8.7         # Updated to latest version for video functionality

  # Fonts
  google_fonts: ^6.1.0         # Updated to latest version for Google Fonts

  # Email functionality
  mailer: ^6.1.0              # For sending emails via SMTP

  # Animations
  animate_do: ^3.3.4          # For beautiful animations in flight details

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0        # Updated to latest version for linting

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/vegas.jpg
    - assets/images/paris.jpg
    - assets/images/venecia.jpg
    - assets/images/
    - assets/video/fondo.mp4